### ISSUE TITLE
How do you use this with multiple plugins?

### ISSUE THREAD

**Issue by optikalefx** [jeffjewiss/ember-cli-postcss#109]
When I use a single plugin, it works fine. But when I use

```
postcssOptions: {
      compile : {
        plugins: [
          { module: require('autoprefixer') },
          { module: require('postcss-scss') }
        ]
      }
    }
```

I get this error

```
The Broccoli Plugin: [PostcssCompiler] failed with:
TypeError: plugin.module is not a function
```

What am I missing?

Thanks!

**Comment by jeffjewiss** [comment]
Hi @optikalefx, which version of the add-on are you using? I've tested 3.4.0 and 3.4.1 with a personal project and it appears to be working fine with multiple plugins.

Your configuration looks fine to me. Based on the error it seems like one of the plugins isn't being required properly. Is it possible either `autoprefixer` or `postcss-scss` is missing from your `package.json` or maybe wasn't installed before the Ember app was built?

**Comment by optikalefx** [comment]
Thanks. It looks like it was one of my plugins that just wasn't up to date causing all the issues.

Thanks!

**Comment by jeffjewiss** [comment]
No problem, glad to hear you got it sorted out!
