### ISSUE TITLE
Support for addons

### ISSUE THREAD

**Issue by pixelhandler** [jeffjewiss/ember-cli-postcss#12]
I was not able to use this addon for addons see https://pixelhandler.com/posts/developing-ember-addons-next-generation-css-with-postcss

Do you think this addon can support building styles for addons ?

**Comment by jeffjewiss** [comment]
Hi Bill, sorry for taking so long to respond. The addon in its current state isn't really setup to build styles that are imported from other addons.

However, I've been working on refactoring the addon to add some basic tests and to add support for using postcss as a compile step (it's current form) and also as a filter/postprocessor step, which should happen after other processors run and addons add files to the broccoli tree or vendor file.

Could you please try out this update and see if it works for your use case? I've updated the readme with new instructions here: https://github.com/jeffjewiss/ember-cli-postcss/tree/refactor and you should be able to install it with `ember-cli-postcss: "jeffjewiss/ember-cli-postcss#refactor"` in your package.json.

My intent is to publish this refactored version as V3.0, but I'd like to see if it solves your use case first.

Thanks!

**Comment by pixelhandler** [comment]
@jeffjewiss thanks for the update. I'll try out that branch soon. Regarding my use case, I ended up blogging here ... https://pixelhandler.com/posts/developing-ember-addons-next-generation-css-with-postcss  

Also here are some example apps that share an addon with styles https://gitlab.com/u/pixelhandler/projects this is the styles addon https://gitlab.com/pixelhandler/xyz-styles

**Comment by jeffjewiss** [comment]
Thanks @pixelhandler, yeah the refactor of the add-on should support your use case as setup in the example app you linked to without having to use `broccoli-postcss` in the custom add-on. If you use the new filter method in the refactor, it should run on any styles that are added to the main app broccoli tree and also to the vendor styles as well.

Do you know when you'll have a chance to give this a try? I'd like to release the new version soon, but was really hoping someone could try it on projects other than my own. Thanks again!

**Comment by pixelhandler** [comment]
@jeffjewiss I have not been able to lend time to this effort lately, sorry about that. Perhaps try this repo out, https://gitlab.com/pixelhandler/xyz-styles its an addon, replace the custom use of broccoli-postcss with the ember-cli-postcss/tree/refactor features. Then try and use the xyz-styles addon in https://gitlab.com/pixelhandler/xyz-foundation that's what I plan to try.

**Comment by rwwagner90** [comment]
Any updates on this? Trying to determine if/when I should move away from SASS.

**Comment by pixelhandler** [comment]
@rwwagner90 for Addons I have been using `broccoli-postcss`, `autoprefixer`, `postcss-cssnext`, `postcss-import` in my build see https://gitlab.com/pixelhandler/xyz-styles/blob/master/index.js#L24-53

**Comment by jeffjewiss** [comment]
@rwwagner90 do you mind explaining your use case in a bit more detail?

My understanding is that add-on CSS gets added to the vendor styles tree, so if you use V3 of this add-on and specify some plugins for the filter option they should get applied to the styles in the vendor tree at the end of the build process.

Alternatively, if you're looking to organize your CSS files and import them you can do so using the `postcss-import` plug-in and import files from within your project or from NPM modules and organize your styles that way.

**Comment by rwwagner90** [comment]
@jeffjewiss it's been quite awhile since I first looked into this, so I am not sure exactly what didn't work. I have various use cases, but the base case is having an addon's css correctly useable. For example, I have a navbar addon, that needs styles to work. So, the styles need to end up in the vendor tree for sure.

**Comment by jeffjewiss** [comment]
@rwwagner90 thanks for replying. The version of ember-cli-postcss that supports a filter method for working with the vendor tree was published a week or two ago.

How do you currently support this with a Sass workflow? Do you need to do anything special in your addons or do they it work as is?

Thanks!

**Comment by jeffjewiss** [comment]
I'm going to close this issue since it should be resolved with the addition of the filter/compile methods and @ef4's work to ensure that the configuration is correct for scoping the settings to add-ons.

If the latest version doesn't work for your use case, please open a new issue or comment here and I'll re-open this one. Thanks!
