### ISSUE TITLE
Postcss parsers

### ISSUE THREAD

**Issue by PixelJanitor** [jeffjewiss/ember-cli-postcss#131]
Is it possible to add a parser like https://github.com/postcss/postcss-scss with the ember-cli-postcss in the `postcssOptions`? If so, what would that look like? Thanks

**Comment by PixelJanitor** [comment]
Wanted to add that I tried this :

```
    postcssOptions: {
      compile: {
        enabled: true,
        parser: require('postcss-scss'),
        plugins: [
          {
            module: require('precss'),
          },
          {
            module: require('postcss-cssnext'),
            options: {
              browsers: ['last 2 versions'],
            },
          },
        ],
      },
    },
```

but the output isn't affected

**Comment by jeffjewiss** [comment]
Hey @PixelJanitor, the config you shared should work in adding the Sass parser.

Do you mind sharing an example of your input and what the expected output would be?

My understanding is that the parser you referenced only parses mixins and variables:

> This module does not compile SCSS. It simply parses mixins as custom at-rules & variables as properties, so that PostCSS plugins can then transform SCSS source code alongside CSS.

If you're looking to transition a project from Sass to Postcss, you may need to use something like this plugin: https://github.com/arpadHegedus/postcss-node-sass but I haven't tried it yet. I'm working on setting up a blueprint and example project for switching from Sass to Postcss but haven't finished it yet.

Let me know about the above and I'll see if I can help figure out a solution.

Cheers

**Comment by jeffjewiss** [comment]
Just an update on this, you should be able to use a config like this: https://github.com/jeffjewiss/ember-cli-postcss/blob/master/blueprints/postcss-sass/files/ember-cli-build.js if you'd like to use both Sass and Postcss together.

Does that handle your use case?

**Comment by PixelJanitor** [comment]
Thanks for the info on this, Jeff. Sorry for the delayed response. That config you shared helped a lot! Thanks 👍

**Comment by jeffjewiss** [comment]
No worries, glad you got it sorted Derek! Cheers.
