### ISSUE TITLE
3.6.1 is incompatible with Node 4 w/yarn

### ISSUE THREAD

**Issue by kevinansfield** [jeffjewiss/ember-cli-postcss#133]
I see in https://github.com/jeffjewiss/ember-cli-postcss/commit/e2689661af5686aa655e0ffb88a786cd30059173 that support for Node 4 was dropped which prevents this package from being installed via `yarn` when using Node 4.

Node 4 is still an active LTS version, is there something specific in this addon that is incompatible? At Ghost we follow Node's LTS schedule so we need to still need to support v4, I was a bit surprised when a patch version update killed our Travis builds.

**Comment by jeffjewiss** [comment]
Thanks for reporting this and sorry for the broken builds.

I was trying to speed up builds since I'm testing against 4 Node versions and 5 Ember versions.

I have no problem continuing to support Node 4 until it's no longer LTS. I should be able to release a new patch version in an hour or two.

**Comment by jeffjewiss** [comment]
Please let me know if there are any issues with v3.6.2 and Node 4.

Again, sorry about the broken builds.

Cheers.

**Comment by kevinansfield** [comment]
👍 all good now, thanks for the quick turnaround! 😄 It's going to be a good day in April when v4 is finally put to rest
