### ISSUE TITLE
Use of ember-cli-postcss in addons

### ISSUE THREAD

**Issue by mansona** [jeffjewiss/ember-cli-postcss#135]
Hi folks 👋 

I'm working on an addon that needs to process postcss as part of the addon's css. Ideally, I would love for the addons **processed** css to be a part of vendor.css and for the consuming app to not have to care about it but I would be ok with a system where you need to do something like `add @import 'my-cool-plugin.css'; to /app/styles/app.css.` (found in the now defunct: https://github.com/adfinis-sygroup/ember-adcssy) 

Any advice on how to proceed would be very helpful

**Comment by jeffjewiss** [comment]
Hey @mansona!

Is the goal to be able to use postcss for authoring the addon's styles, but without a need to modify them in the app that consumes the addon? If so, as long as you create your styles in `addon/styles/addon.css` and setup the build config for your addon to process postcss those styles should end up in `vendor.css` of the consuming app.

You can see a good example of this configuration and setup in one of the **cardstack** repos here: https://github.com/cardstack/cardstack/tree/master/packages/tools

You can test to confirm that this works be creating a new app with `ember new` and then installing `@cardstack/tools` and `@cardstack/plugin-utils` and running a build. You'll see the styles from the tools plugin in the created `vendor.css`.

Please let me know if you have any questions about that or if you'd like to discuss taking a different approach.

Cheers!

**Comment by mansona** [comment]
@jeffjewiss the thing I was missing was the `options` block in the index.js. I didn't even know you could do that! thanks for the example 👍

**Comment by jeffjewiss** [comment]
Okay great, glad to hear you got it sorted!

**Comment by mansona** [comment]
@jeffjewiss just out of interest... do you think this should be documented anywhere? like a wiki page for "so you're developing an addon and you want to use postcss"?

**Comment by jeffjewiss** [comment]
@mansona yeah, I think that's a great idea. My eventual goal is to have a GitHub pages website with instructions for the different use cases of postcss + ember, but I haven't had time to build it just yet. As a first step I added a section to the bottom of the readme: https://github.com/jeffjewiss/ember-cli-postcss#developing-addons with the example from this issue. Do you think this provides enough guidance until more in-depth documentation is ready?

Cheers

**Comment by mansona** [comment]
that's perfect, my main issue was not even knowing where to start 😖  thanks a million
