### ISSUE TITLE
Add configuration examples to Docs

### ISSUE THREAD

**Issue by jeffjewiss** [jeffjewiss/ember-cli-postcss#136]

**Comment by samselikoff** [comment]
I'm trying to follow the install instructions for an addon I'm writing, but I can't figure out where to put the config.

I'm trying to get my addon's dummy app working.

The only way I've been able to get it working is

```
let app = new EmberAddon(defaults, {
  postcssOptions: {
    compile: {
      enabled: true,
      plugins: [
        { module: CssNext }
      ]
    }
  }
});
```

but that's obviously only for my dummy app - I want my addon to set this up for my dummy app.

I tried this

```
// my-addon/config/environment.js
'use strict';
const CssNext = require('postcss-cssnext')

module.exports = function(/* environment, appConfig */) {
  return {
    postcssOptions: {
      compile: {
        enabled: true,
        plugins: [
          { module: CssNext }
        ]
      }
    }
  };
};
```

and this

```
// index.js
'use strict';

const CssNext = require('postcss-cssnext')

module.exports = {
  name: 'ember-cli-tailwind',

  config(environment, appConfig) {
    return {
      postcssOptions: {
        compile: {
          enabled: true,
          plugins: [
            { module: CssNext }
          ]
        }
      }
    };
  }
}
```

but they don't work (I get the error about

**Comment by jeffjewiss** [comment]
I'm sorry to hear this has been frustrating to setup.

Could you please confirm how you'd like the options to work? Is the goal to have part of your addon's build process set or modify the settings for `ember-cli-postcss` in the dummy app?

Currently, only options set from 'ember-cli-build.js' are use by the addon, which I think is why your first example worked, but not the second. The third example might work if `ember-cli-tailwind` ran before `ember-cli-postcss` and then the options would be available. If I remember correctly, the addons are run in alphabetical order (or how they're discovered in a package.json) unless the before/after keys are specified in the package.json (ie. https://github.com/jeffjewiss/ember-cli-postcss/blob/master/package.json#L57).

So you might be able to get the third example working with that key.

Alternatively, would it be useful if I changed how the addon options worked and merged options from `ember-cli-build.js` and the environment config (if possible)?

**Comment by eshtadc** [comment]
I may have something similar. I'm trying to include `ember-cli-postcss` in an addon I'm writing for shared settings I want across several Ember applications. I'd like to set the base configuration options in my addon to be consumed by `ember-cli-postcss` as if they were in the application's `ember-cli-build.js` file. If I'm reading your response here correctly, `ember-cli-postcss` explicitly only reads from the top-level application. Is this correct? Is there a work-around or solution for addon developers to provide base/default configuration options?

**Comment by rickieshi** [comment]
Not sure this is 100% related, I was working on an in-repo engine and the way I ended up to get config working was to 
- follow comment above to `add the "before" ["ember-cli-postcss"] to my package.json`
- in `index.js` of in-repo engine, add the following directly without wrapping it inside `options`
```javascript
  // index.js
  const { join } = require('path');
  const style_dir = join( __dirname, 'addon', 'styles');
  // ...
  isDevelopingAddon() {
    return true;
  },

  postcssOptions: {
    compile: {
      extension: 'css',
      includePaths: [style_dir],
      plugins: [{ /* ... */ }]
    },
    filter: {
      enabled: false
    }
  } 
```

**Comment by gokatz** [comment]
Thanks, @rickieshi. Your configuration works for me to add PostCSS in Ember Engines. Maybe we can add this under the [Addon Dev section](https://github.com/jeffjewiss/ember-cli-postcss#developing-addons).

**Comment by btecu** [comment]
When using the `index.js` approach, if nothing is set in `ember-cli-build.js` (for the dummy), I get:
`You must provide at least 1 plugin in the plugin array`.

**Comment by jeffjewiss** [comment]
If `postcssOptions.compile.plugins` or `postcssOptions.filter.plugins` (whichever one is relevant) is empty this add-on will complain because postcss won't do anything without running at least one plugin.

If you don't want to run it with your dummy config you'll need to set `compile.enabled` to false.

**Comment by jrowlingson** [comment]
I am seeing a similar result as @btecu when using the `index.js` approach. Here, I am setting `plugins` so that it is not empty.

**Comment by jeffjewiss** [comment]
Thanks for the feedback, I haven't recently use this with an Ember Engine addon approach.

@jrowlingson yes, I think the docs should be updated with better information on how to configure add-ons, including engines. Do you have time to submit a PR as you're likely more familiar with the setup? Thanks!

**Comment by NullVoxPopuli** [comment]
I'm currently trying to make an addon that provides a PostCSS config. 
This is what I have so far:
```ts
// addon's index.js
module.exports = {
  name: require('./package').name,

  isDevelopingAddon() {
    return true;
  },

  included(app) {
    this._super.included.apply(this, arguments);

    app.options = app.options || {};

    app.options.postcssOptions = {
      filter: {
        enabled: false,
      },
      compile: {
        plugins: [
          {
            module: PostCSSImport,
            options: {
              path: [shoelacePath]
            }
          },
          {
            module: PostCSSNext,
            options: {
              features: {
                colorFunction: {
                  preserveCustomProps: false,
                },
                customProperties: {
                  preserve: true,
                },
                rem: false,
              },
            }
          }
        ],
      },
    }
  }
};
```

and then
```ts
// consuming app's ember-cli-build.js
  let app = new EmberApp(defaults, {
    // ...
    postcssOptions: {
      compile: {
        enabled: true
      },
      filter: {
        enabled: false
      }
    }
  });

```

and I'm currently getting 
```
Build Error (PostcssCompiler)

You must provide at least 1 plugin in the plugin array
```

**Comment by mjzefeldt** [comment]
@NullVoxPopuli - Thanks for posting this this approach. Question, do you have ember-cli-postcss installed in both the addon and the consuming app?  I want the consuming app to take advantage of the addon postcss config - but have only been able to get this to work with ember-cli-postcss installed in both addon and consuming app.

**Comment by jherdman** [comment]
I'm fairly certain it's impossible to use ember-cli-postcss to compile `addon.css` such that host apps need only include the finalized output.

The first hint is that you need to add ember-cli-postcss as a direct dependency. Once you do this it will attempt to read `addon.css` (yay!).

Next add your config to index.js:

```javascript
included(app) {
    this._super.included.apply(this, arguments);

    app.options = app.options || {};

    options.options.postcssOptions = {
      compile: {
        plugins: [/* ... */]
    };
}
```

A smatter of debuggers will show that there are two passes through ember-cli-postcss. The first pass does NOT pick up your options and thus the default `compile` settings will eventually fail. The second pass DOES pick up your settings and _should_ work.

I cannot, for the life of me, figure out a workaround.

**Comment by jeffjewiss** [comment]
Sorry this is so frustrating. I haven't worked on the addon integration part of ember-cli-postcss in a while, but I don't think I ever found a great solution to play nicely with how ember-cli handles some of the trees through broccoli.

Re: Edit 3: Aside: I don't think there's a good reason other than to fail early and make it clear to users of the addon that their styles aren't being processed. I'm open to changing this.

Would having the no-op or warning instead of failing help with this use case? Would that allow it to skip the first processing of styles and catch it the second time?

**Comment by jherdman** [comment]
Hey Jeff. In the end I found that @NullVoxPopuli 's solution worked for me. The key seems to be configuring in `included` _and_ having the options set directly on the `index` object. `¯\_(ツ)_/¯`
