### ISSUE TITLE
SASS-like blueprint

### ISSUE THREAD

**Issue by mike-north** [jeffjewiss/ember-cli-postcss#19]
I'm working on a blueprint that will set a consuming app's `ember-cli-blueprint.js` with a SASS-compatible post-css plugin stack. There has been a lot of excitement around postcss in the ember community, but SASS has by far the most adoption. This will give people an easy way to switch over cleanly, and then add more plugins from there.

**Comment by jeffjewiss** [comment]
I'd love to collaborate on this and create some options for the blueprint around which plugins get added, setting up or disabling source maps and eventually setting up CSS stats.

This sounds great, let me know how I can help.
