### ISSUE TITLE
Cannot generate sourcemaps

### ISSUE THREAD

**Issue by ismay** [jeffjewiss/ember-cli-postcss#2]
As far as I can tell, this addon does not allow for any options, other than the plugins array, to be passed to broccoli-postcss. In turn broccoli-postcss does not seem to accept options for configuring sourcemap generation (but from what I can tell, it should [generate a separate sourcemap by default](https://github.com/jeffjewiss/broccoli-postcss/blob/master/index.js#L37). In the generated css, ember-cli-postcss *does* add a comment referring to a sourcemap:

`/*# sourceMappingURL={app-name}.css.map */`

But the sourcemap itself is never generated. Should ember-cli-postcss be generating a sourcemap currently, or is that still under development?

**Comment by ismay** [comment]
Inline sourcemap generation does work with `map: true` (set in https://github.com/jeffjewiss/broccoli-postcss/blob/master/index.js#L40):

```javascript
    var options = {
        from: fromFilePath,
        to: toFilePath,
        map: true
    };
```

So the problem might be related to the `.map` extension being funnelled out.

**Comment by ismay** [comment]
> So the problem might be related to the `.map` extension being funnelled out.

Seems to be related to `result.map` not being handled in broccoli-postcss.

**Comment by knownasilya** [comment]
Was this ever fixed?

**Comment by jeffjewiss** [comment]
Yes, I believe so. I'm confident inline source maps work as I'm currently using them, but I haven't tested the options being passed properly for source map file creation, which was added in `broccoli-postcss` 2.1.0. It should work, so I'm going to close this issue. I'll reopen it if I hear or experience otherwise.
