### ISSUE TITLE
CSS returns 404 when using ember serve

### ISSUE THREAD

**Issue by ashleyconnor** [jeffjewiss/ember-cli-postcss#22]
I followed the `autoprefixer` example in your readme but the CSS does not resolve when serving with `ember serve`.

`ember build` compiles the CSS correctly but puts the resulting file in `dist/app/styles` which I believe should be `dist/assets`.

Possibly a 2.7 thing? Or just some misconfiguration on my end. If so the examples possibly need updating.

Repo is here:
[https://github.com/ashleyconnor/mapledeals_frontend](https://github.com/ashleyconnor/mapledeals_frontend)

**Comment by jeffjewiss** [comment]
Thanks for submitting this and a repo with a reproducible error case.

I looked into this a bit and I can see what's happening in the add-on that's causing this, but I'm not quite sure why just yet. The current implementation of `filter` sort of assumes that you're using another CSS processor, so when you only use `filter` your `app.css` file doesn't properly get renamed and written to the `dist/assets` directory, as you mentioned. I think this may be a unique case for the `app/<app-name>` CSS file, but I need to look into it a bit further.

I'll leave this issue open to track my progress on coming up for a fix to the add-on and the documentation.

In the meantime, if your plan is to use Postcss as your main CSS processor in the repo you linked to, you should be able to switch from using `filter` to `compile` and have it work as expected until I can figure out a fix. If you'd like autoprefixer to run on the `vendor.css` as well, you may need to run `compile` **and** `filter` until I can get a fix working to run `filter` as the only CSS processing step.

**Comment by ashleyconnor** [comment]
Switching from `filter` to `compile` worked.

I also noticed last night that some repos that I rely on cause errors when using `filter` (the `filter` was picking up sample CSS from a downstream dependency - https://kjur.github.io/jsrsasign/).

Possibly a future feature would be to white/black list vendor dependencies.

I appreciate the reply and thank you for this awesome project 👍

**Comment by jeffjewiss** [comment]
Thanks for following up, I'm glad compile is working for you!

Yeah, I think a white/black list is a good idea for filtering. It could possibly use the addon's name or maybe a glob pattern. Do you mind filing that as a separate issue?

**Comment by jeffjewiss** [comment]
I'm going to close this as it's now possible to white/black list dependencies by using the include/exclude options with filter. Thanks!
