### ISSUE TITLE
Glimmerjs Support

### ISSUE THREAD

**Issue by robert-j-webb** [jeffjewiss/ember-cli-postcss#297]
Hi!

So I have been using this project for my ember app, but we are now making a glimmer version of this app. It works! However I did have to delete one line of code for it, and I'm sure if you wrap it in a 'isEmber' check then, that would be fine. Here's my fork that works for me:
https://github.com/robert-j-webb/ember-cli-postcss/blob/master/index.js#L68

You can see I just deleted this line: https://github.com/jeffjewiss/ember-cli-postcss/blob/master/index.js#L70

I don't think it would be too difficult for me to clean this up with an isEmber check and merge upstream if you'd like

**Comment by jeffjewiss** [comment]
Hey, thanks for reporting this!

I'd love for this add-on to support glimmer apps. If you don't mind cleaning up your fork into a pull request I'd be happy to merge the change in. Do you think having a line in the readme as well would help others working on glimmer apps?

Cheers!

**Comment by robert-j-webb** [comment]
Sure thing, I'll figure this out and make a PR for you!
