### ISSUE TITLE
baseURL/rootURL

### ISSUE THREAD

**Issue by leifdejong** [jeffjewiss/ember-cli-postcss#31]
After installing I am getting this error ```WARNING: The `baseURL` and `rootURL` settings should not be used at the same time.```. Believe this has to do when ember moved to rootURL instead of baseURL in 2.7.

**Comment by leifdejong** [comment]
@jeffjewiss Found that your v3.0.4 release has the baseURL in `config/environment.js`. Any chance you might be able to cut a new release with the updates for rootURL?

**Comment by jeffjewiss** [comment]
Thanks for reporting this! I've just published v3.0.5, do you mind confirming that this removes the `baseURL` warning?

**Comment by leifdejong** [comment]
@jeffjewiss all set! You're the man. Thanks a lot!
