### ISSUE TITLE
`resolve`'d filenames not fingerprinted

### ISSUE THREAD

**Issue by nanuxbe** [jeffjewiss/ember-cli-postcss#35]
When using `resolve` (from https://github.com/assetsjs/postcss-assets) the resolved filenames don't get fingerprinted in the final css output.

This probably comes from postcss hooks being run after https://github.com/rickharrison/broccoli-asset-rev 's hooks.

**Comment by jeffjewiss** [comment]
@nanuxbe thanks for reporting this. I haven't used `postcss-assets` myself, but it seems like it should work with this addon.

You're probably right about the hook order. It should be possible to fix that by telling this addon to run before `asset-rev`. With that in mind, could you please try this branch: https://github.com/jeffjewiss/ember-cli-postcss/tree/asset-rev-hooks and let me know if that fixes the issue for your project?

Thanks!

**Comment by jeffjewiss** [comment]
I've updated the `package.json` as I mentioned above, which should solve the issue. I'll be publishing this as 3.0.6. Please let me know if you're still experiencing this issue and we can reopen the ticket. Thanks for reporting it!
