### ISSUE TITLE
Trees Are Post Processed Twice

### ISSUE THREAD

**Issue by benmurden** [jeffjewiss/ember-cli-postcss#408]
I noticed that because filters are set to run on `all` and `css` trees, they run twice when doing a production build.

https://github.com/jeffjewiss/ember-cli-postcss/blob/93aeb3d5973ffb2fd2ea0dd1c470c8c9777c9aac/index.js#L66

Is this a sensible default? Builds seem to run down all trees sequentially, including `all`.

**Comment by jeffjewiss** [comment]
Thanks for reporting this. I think this was setup to run on 'all' and 'css' for historical reasons, but I'm not sure if it's still relevant. The types for the `postprocessTree` hook aren't documented in a lot of detail.

Have you tried setting the `processTrees` option to `css` for your app? Does that work as intended for al environments? I'm wondering if that would be a better default or if it needs to be changed just for the production environment.

**Comment by benmurden** [comment]
In the **development and test** environments, the following trees run:

```terminal
template
js      
css     
test    
all
```
In the **production** environment, the following trees run:

```terminal
template
js
css
all
```
Only difference in trees seems to be that the test tree is not included in production builds. Otherwise, all trees run.

If I limit `processTrees` to `css` then it runs only once as expected.

**Comment by jeffjewiss** [comment]
Thanks for following up on this. I'm going to update the default to be just the `css` tree and I'll have a new version published soon.
