### ISSUE TITLE
trouble using ember-cli-postcss with postcss-purgecss

### ISSUE THREAD

**Issue by greyhwndz** [jeffjewiss/ember-cli-postcss#420]
I am currently using:
```
λ ember -v
ember-cli: 3.10.1
node: 10.15.3
os: win32 x64
```
and my `app/styles/app.css`:
```
@import "ember-modal-dialog/ember-modal-structure.css";
@import "ember-modal-dialog/ember-modal-appearance.css";
@import "tailwindcss/base";
@import "custom-base";
@import "tailwindcss/components";
@import "custom-components";
@import "tailwindcss/utilities";
@import "custom-utilities";
@import "tailwindcss/screens";
```
and my `ember-cli-build.js`:
```
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const { join } = require('path');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    postcssOptions: {
      compile: {
        plugins: [{
            module: require('postcss-import'),
            options: {
              path: ['node_modules']
            }
          },
          require("tailwindcss")("./config/tailwind.config.js"),
        ]
      },
      filter: {
        enabled: true,
        plugins: [
          require('@fullhuman/postcss-purgecss')({
            content: [
              join(__dirname, 'app', '**', '*.html'),
              join(__dirname, 'app', '**', '*.hbs'),
              join(__dirname, 'app', '**', '*.js'),
            ],
            defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
          })
        ]
      }
    }
  return app.toTree();
};
```

It seems like `purgecss` is removing the `ember-modal-dialog` css is getting removed despite using:
```
{{#modal-dialog}}
   Testing Modal Dialog...
{{/modal-dialog}}
```
in the templates.
Whenever I disable the purgecss filter the modal gets styled correctly.

**Comment by jeffjewiss** [comment]
I think the issue here is that purgecss is running on your app code as an HBS template and so it doesn’t know that it has css classes on the component. This is likely true of any dynamic css class or those bound to a component using classNames. This is normally avoided by running purgecss on your app’s js, but I’m not sure how smart the purgecss parser is or how Ember aware it is. You might be able to get around this by adding the modal dialogue package path to your content array in the purgecss options.

**Comment by steveszc** [comment]
I encountered this issue as well. 
I think it would be pretty common for anyone using `ember-cli-postcss` with `postcss-purgecss` to experience vendor styles (styles added to vendor.css by addons) being incorrectly stripped from vendor.css. Many addons provide css that is neccesary for the addon's components to function properly, but these classes often only show up in the addon's templates, not in the consuming app's templates.

Here is a fix. This prepends a comment to your vendor.css file that will tell purgecss to ignore the file's contents.

ember-cli-build.js
```js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {});

  app.import('vendor/purgecss-ignore.css', { prepend: true });

  return app.toTree();
};
```

vendor/purgecss-ignore.css
```css
/* purgecss start ignore */
```
