### ISSUE TITLE
postcss-sass errors

### ISSUE THREAD

**Issue by devotox** [jeffjewiss/ember-cli-postcss#499]
```
You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
```

```

	'postcssOptions': {
		compile: {
			enabled: true,
			extension: 'scss',
			// map: isDevelopment,
			parser: require('postcss-scss'),
			plugins: [
				{ module: require('@csstools/postcss-sass') },
				{ module: require('cssstats') },
				{ module: require('postcss-stats-reporter') },
				{ module: require('postcss-reporter') }
```

**Comment by jeffjewiss** [comment]
Could you please provide a bit more information about the issue? Is this on a newly generated Ember app? What does the rest of your `ember-cli-build.js` file look like and what versions of `ember-cli`, `ember-source` and `ember-cli-postcss` are you using?

**Comment by devotox** [comment]
Ok after a long debugging session. It seems the issue is the combination of 
- '@csstools/postcss-sass@4.0.0'
- 'emberfire@3.x.x'

Where would be the best place to report this and do you think it will even be looked into as I have no idea how one could be affecting the other

**Comment by jeffjewiss** [comment]
Sorry, I'm not sure I can help without more information.

Are you able to share the app/repo you're working on? Does your app work without ember-cli-postcss or postcss-sass?

This addon doesn't use `wasm` or have mappings, so it seems like it might be caused by emberfire.

**Comment by devotox** [comment]
Ok so postcss-sass does use SourceMapConsumer but this error only pops up when emberfire is included
