### ISSUE TITLE
Cannot find module 'bootstrap/package.json'...

### ISSUE THREAD

**Issue by Subaku** [jeffjewiss/ember-cli-postcss#533]
Getting this error in my attempt to move away from ember-cli-sass:
`Cannot find module 'bootstrap/package.json' from '/Users/bmurphy/projects/tv2/tvwebapp/ember/inventory'`

Which this configuration:
```
postcssOptions: {
      compile: {
        extension: 'scss',
        enabled: true,
        parser: require('postcss-scss'),
        plugins: [
          {
            module: require('@csstools/postcss-sass'),
            options: {
              includePaths: [
                'node_modules',
              ],
            },
          },
        ]
      },
      filter: {
        enabled: true,
        plugins: [
          {
            module: require('autoprefixer'),
          }
        ]
      },
    }
```
So far I've not had a single successful build working with this plugin. Bit confused...
What's the bare minimum config I need in order to just compile scss to css and use the autoprefixer plugin?

Note that given what the error says this is my `app.scss` file:

```
@import 'main';

/*****  Vendor *****/

@import "ember-bootstrap/bootstrap";
@import 'ember-power-select/themes/bootstrap';
@import 'ember-power-select';
@import 'vendor/spinkit';


/***** Components *****/

@import 'components/asset-location-summaries/main';
@import 'components/asset-locations/main';
@import 'components/asset-type-filter/main';
```

So nothing fancy. Commenting out those vendor imports also doesn't do anything either.

Appreciate any help :)

Ember-CLI: 3.14.0
Ember-CLI-Postcss: 5.0.0

**Comment by deathaz** [comment]
@Subaku Looks like your `package.json` didn't have `bootstrap` as dependencies, this should be not related to ember-cli-postcss because this error output from `ember-bootstrap` when it resolving `bootstrap` package.

if this issues still exist, you should copy your `ember-cli-build.js`, `package.json` and `app.scss` to here or you can simulate and publish a repo for me to have a look.

**Comment by jeffjewiss** [comment]
This add-on shouldn't be looking for or reading any `package.json` files. Are you sure the error is coming from this add-on and not `ember-bootstrap` as @deathaz mentioned?

What you've shared should work, but `@csstools/postcss-sass` works differently than normal Sass configuration, so there are some differences between using the two and they aren't 100% compatible.
