### ISSUE TITLE
how can I make this concat component styles?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jeffjewiss/ember-cli-postcss#534]
I'm wanting to co-locate CSS with a few components, is there a way to concat all those together before running postcss? they could just be appended to the bottom of app.css during the build

**Comment by jeffjewiss** [comment]
Why do you need to concat them before running Postcss? Could this be accomplished by using `postcss-import` as the first plugin, and then running your other plugins after?

If you need to combine the files first, you'll probably need to use something like `broccoli-concat` in your `ember-cli-build.js` file before running postcss or you could create an in-repo add-on to do something similar.

This add-on supports operating on multiple files in the compile step, but it then outputs files of the same name one to one.

**Comment by NullVoxPopuli** [comment]
> Why do you need to concat them before running Postcss? 

Because I think I want all my variables and mixins readily available without importing.

I guess it could be done with imports, but I'd have to restructure everything. And I'm also working with shoelace-css, which I didn't write, so I'd need that to work.

> If you need to combine the files first, you'll probably need to use something like broccoli-concat in your ember-cli-build.js file before running postcss or you could create an in-repo add-on to do something similar.

how would that work? I briefly googled / looked in to how I could tie in to the existing style pipeline, but couldn't figure it out.

> This add-on supports operating on multiple files in the compile step, but it then outputs files of the same name one to one.

but if it's all just pipelines, does the order matter?

**Comment by jeffjewiss** [comment]
> Because I think I want all my variables and mixins readily available without importing.

> I guess it could be done with imports, but I'd have to restructure everything. And I'm also working with shoelace-css, which I didn't write, so I'd need that to work.

Sorry, I'm not familiar with shoelace-css or its structure.

I was under the impression that Postcss would need to parse your files for the mixins, etc. to work, so I thought you'd effectively have the same situation if they're in the same file or imported. Does shoelace normally handle this for you?

> how would that work? I briefly googled / looked in to how I could tie in to the existing style pipeline, but couldn't figure it out.

I don't think I'd recommend this option and I don't think it would be simple. The reason the order matters is that when the postprocessor hook is run for this addon (ember-cli-postcss) it writes/moves the app.css file for your app from the source to the broccoli destination tree. This is why if you want to use ember-cli-sass and ember-cli-postcss you need to use the "filter" step. Two addons can't operate on the same style file if they're writing to the destination/output tree.

I think to support what you're after you'd need to do something similar to what's done in ember-component-css around here: https://github.com/ebryn/ember-component-css/blob/3d41b40e89aaa5c7d280fcd7b5c592125b6ce135/index.js#L206

My understanding is that they're using https://github.com/webark/broccoli-file-manifest and a broccoli funnel to write a new file 'pod-styles.css' to the tree, which can then be imported in app.css. This new style file contains all of the component styles.

I'm open to supporting this importing functionality in ember-cli-postcss, but I don't know how long it would take to implement, test and make configurable or what the timeline is like for your project.

**Comment by NullVoxPopuli** [comment]
hmm. ember-component-css is what I was using before I went down the ember-css-modules path.

It's totally possible I did all this exploration for nothin'. lol. 

j/k, lots of learning. 
I think in general, we need better file manipulation primitives. or maybe I need to learn more about broccoli. _hmm_.

thanks! I think I'll go back to concat with ember-component-css once they support co-located components (the reason that started this dark adventure, is that css-modules had support and component-css did not)

**Comment by jeffjewiss** [comment]
Ah, well that's frustrating, sorry I couldn't be more help.

The broccoli stuff is pretty opaque, which is why I ended up creating a couple broccoli plugins to power this addon.

Let me know if you think adding co-located style files would be useful to support for this addon. I think it could work in a similar way to ember-component-css.

I'll consider this issue closed for now, thanks.
