### ISSUE TITLE
Doesn't run in production

### ISSUE THREAD

**Issue by bnetter** [jeffjewiss/ember-cli-postcss#570]
👋 I've been using your add-on to compile Tailwind, on top of my Stylus stack. It's working perfectly in development environment, but it feels like it's completely ignored in production and staging environment.

Here's what I have in my `ember-cli-build.js`:
```
postcssOptions: {
  compile: {
    enabled: false
  },
  filter: {
    enabled: true,
    plugins: [ tailwind ]
  }
}
```

It works perfectly fine on my local environment: replacing `@apply` after Stylus ran. In production, Stylus runs, but not PostCSS.

Do you have any idea?

**Comment by bnetter** [comment]
Hum, actually it's weird… if I run `ember install ember-cli-postcss`again, it works. It's weird because I still have it in my `package.json` and just ran `npm install`.

**Comment by jeffjewiss** [comment]
Is it possible that the add-on was missing from your node_modules directory? I think `ember-cli` might check that the add-on directory exists before trying to run it, but I'm surprised there wasn't a different error. 

Does it run okay now or is this still an issue?

Thanks
