### ISSUE TITLE
Addon is adding both compiled and non-compiled CSS to vendor.css

### ISSUE THREAD

**Issue by kpfefferle** [jeffjewiss/ember-cli-postcss#581]
We have an internal company addon that just started using ember-cli-postcss to build its CSS. In our consuming application, our `vendor.css` contains *both* the compiled and non-compiled CSS from our addon's `addon.css` (which then breaks ember-cli's minification since the non-compiled CSS includes `&` characters for nesting).

There is a relevant open issue on ember-cli for duplicate addon CSS in `vendor.css` (https://github.com/ember-cli/ember-cli/issues/9076), but I thought I'd also raise this here specifically because we're seeing both the compiled and non-compiled addon CSS appear.

The addon is using the following PostCSS config:

```js
'use strict';

const PostCSSPresetEnv = require('postcss-preset-env');
const { join } = require('path');
const style_dir = join(__dirname, 'addon', 'styles');

const postcssOptions = {
  compile: {
    enabled: true,
    extension: 'css',
    includePaths: [style_dir],
    plugins: [
      {
        module: PostCSSPresetEnv,
        options: { stage: 3, features: { 'nesting-rules': true } },
      },
    ],
  },
};

module.exports = {
  name: require('./package').name,
  options: { postcssOptions },
};
```

**Comment by jeffjewiss** [comment]
Thanks for reporting this.

I don't think there's anything I can do to the add-on to fix the duplicate, but I'll leave this issue open until the `ember-cli` issue is resolved. Thanks.

**Comment by kpfefferle** [comment]
Thanks to @bantic for fixing this in https://github.com/ember-cli/ember-cli/pull/9183 🎉
