### ISSUE TITLE
Option to build css only on the initial serve? 

### ISSUE THREAD

**Issue by deanmraz** [jeffjewiss/ember-cli-postcss#582]
Is there the ability to only build the css on the initial ember serve and subsequent calls it just reuses the same css output?

I use tailwindcss so the css styles typically don't change, but I'm getting 5 second Postcss build times on each js or handlebar template change. Without Postcss it would be less than a second.

**Comment by jeffjewiss** [comment]
What version of this addon are you using? With v6.0.0 changes were made to caching so `hbs` and `js` files should not cause postcss to run, so you should see faster build times.

Let me know if upgrading solves the issue, otherwise we can look into other options. Cheers.

**Comment by deanmraz** [comment]
@jeffjewiss that was it! sorry thought I was on the latest when I tested the cache options. Thanks for the help much appreciated.

**Comment by jeffjewiss** [comment]
Okay awesome! Glad to hear that improved the build times.

You're welcome, thanks for following up on this.
