### ISSUE TITLE
Source maps are included in production build

### ISSUE THREAD

**Issue by manoharank** [jeffjewiss/ember-cli-postcss#61]
By default, source maps are disabled in `ember build --environment=production`. But using `ember-cli-postcss`, source maps are included in app.css.

**Comment by manoharank** [comment]
I have to manually pass `map: EmberApp.env() === 'production'? false : {}` to disable source maps in production buils

**Comment by jeffjewiss** [comment]
Hi @manoharank, thanks for reporting this issue. Could you please confirm if you're using `compile` or `filter` and that the source maps being included in production are inline in your app.css? Thanks!

**Comment by manoharank** [comment]
@jeffjewiss I am using `filter` option. Yes, the source maps are inlined in app.css.

**Comment by jeffjewiss** [comment]
@manoharank thanks for confirming. Could you please try testing your app with [ember-cli-postcss#disable-sourcemaps-production](https://github.com/jeffjewiss/ember-cli-postcss/tree/disable-sourcemaps-production)? I've set sourcemaps to default to disabled unless in the development environment.

Please let me know if you have any questions. Thanks!

**Comment by manoharank** [comment]
@jeffjewiss 👍  

I have tested my app with `disable-sourcemaps-production` branch, it doesn't include source maps in production build. Thanks for the fix!

**Comment by jeffjewiss** [comment]
Thanks @manoharank! I've merged the branch and published `v3.1.2`.
