### ISSUE TITLE
apps, addons, and tailwind specificity

### ISSUE THREAD

**Issue by Techn1x** [jeffjewiss/ember-cli-postcss#661]
Hi! I hope this is the correct place to ask postcss building/pipeline questions. If there's somewhere else I should go please let me know!

I have an app that uses tailwind like this
```js
// ember-cli-build.js
postcssOptions: {
  compile: {
    enabled: true,
    plugins: [
      ...,
      tailwind({ config: { purge: { enabled: isProduction, content: appContentPathsArray } }}),
    ],
  },
  filter: {
    enabled: true,
    plugins: [ ... ],
  },
},
```
```hbs
// application.hbs
<div class="p-6" />
<SomeAddonComponent />
```

I have an addon (consumed by that app) that uses tailwind like this
```js
// index.js
postcssOptions: {
  compile: {
    enabled: true,
    includePaths: [addonStylesDirectory],
    plugins: [
      ...,
      tailwind({ config: { purge: { enabled: isProduction, content: addonContentPathsArray } }}),
    ]
  },
  filter: {
    enabled: true,
    plugins: [ ... ],
  },
},
```
```hbs
// some-addon-component.hbs
<div class="p-6 xl:p-8">
  foo
</div>
```

They create `my-app.css` and `vendor.css` files, with tailwind utility classes in each - `p-6` in the former, and both `p-6` + `xl:p-8` in the latter.

When the above happens (a class defined in both CSS files) we run into specificity issues. Because `p-6` is then also included in `my-app.css`, it causes that `p-6` class to be higher priority compared to `xl:p-8` at XL viewports for the addon component.

I have seen that one solution to this problem is to prefix tailwind classes in addons like `.my-addon-p-6` and `.xl:my-addon-p-8`. For my particular project structure this will be a lot of work (a lot of apps and addons and no easy way to pinpoint tailwind usage)

Has anyone else encountered this, and are there any other solutions other than prefixing?

**Comment by jeffjewiss** [comment]
I think the ideal solution would be to only include the tailwind plugin (and therefore CSS) once in your app. Prefixing the tailwind class would solve the problem, but create duplicate style definitions and prevent the app, which consumes the addon, from customizing tailwind via the config.

There are likely a few ways to accomplish this, but the first I would recommend trying would be to add a boolean config option to your addon's options (something like `enableTailwind`) that would change which postcss plugins are used or if postcss is enabled/disabled. You could then run postcss while developing the add-on to preview the styles, but disable it when consumed by an app and allow the app to be responsible for configuring and running tailwind, so the styles are only included once.

You could try reading this new config setting in the `index.js` of your addon, and then set the appropriate `postcssOptions` value(s).

**Comment by Techn1x** [comment]
Thanks for the tips. In theory I agree I think having Tailwind built once by the app would work well - if I can get it to work :thinking: 

With that goal in mind, the trouble I am having is being able to read addon options from the app, so that the app knows how to build tailwind - specifically so that it has the addon content paths for Tailwind to scan (to avoid purging classes used only by the addon)

Ideally I could define something like this in a hook in the addon's `index.js`
```js
addonTailwindOptions: {
  enabled: true/false,
  content: ['path/to/addon/**/*.hbs', 'path/to/addon/**/*.js']
},
```

And then somehow read/merge/add that into the app's tailwind config object, before the app compiles and includes the tailwind plugin with config (which happens at the `new EmberApp()` step in ember-cli-build.js)

[I tried a few hooks](https://ember-cli.com/api/classes/addon) that are available in `index.js` of the addon, like `included()` and `config()` but that always resulted in the addonTailwindOptions being included in the app options after the tailwind plugin was already built

I'm just a bit confused how to do it - am I on the right path here?

**Comment by Techn1x** [comment]
To follow up on this, I was never able to get the hooks to work in the addon's `index.js` - someone smarter than me might be able to.

The solution I've ended up implementing is;
- continue building tailwind in each app & addon (in order to replace tailwind in directives like `@apply m-1 p-8` in stylesheets)
- each addon no longer includes any tailwind directives in their addon css (eg no more `@import tailwindcss/utilities`), so no more tailwind utility classes in the vendor css.
- both the apps and addons share the same tailwind config for consistency (imported from a separate plugin), except for one difference;
  - addons: have `purge: false` (no tailwind utility classes to purge anyway)
  - app: have purge set to true, and provide a list of paths to known addons via node_modules.

Our tailwind config builder ends up looking like this
```js
const { join } = require('path')
...
module.exports.buildTailwindConfig = function (options = {}) {
  const { isApp = false } = options
  ...
  // The app will include all necessary tailwind utility classes for itself, and its Blake addons
  contentWithTailwindClasses = [
    // the current app itself
    join('.', 'app', 'index.html'),
    join('.', 'app', '**', '*.hbs'),
    join('.', 'app', '**', '*.js'),
    join('.', 'app', '**', '*.ts'),
    join('.', 'translations', '**', '*.json'),
    // look at all addons in the app's node_modules
    join('.', 'node_modules', '@our-namespace', '*', 'addon', '**', '*.hbs'),
    join('.', 'node_modules', '@our-namespace'', '*', 'addon', '**', '*.js'),
    join('.', 'node_modules', '@our-namespace'', '*', 'addon', '**', '*.ts'),
    join('.', 'node_modules', '@our-namespace'', '*', 'translations', '**', '*.json'),
  ]
  return {
    ...commonConfig
    purge: {
      enabled: isApp && isProduction,
      content: contentWithTailwindClasses
    }
  }
}
```
