### ISSUE TITLE
Infinite loop with postcss-color-hex-alpha

### ISSUE THREAD

**Issue by boris-petrov** [jeffjewiss/ember-cli-postcss#665]
Hi,

I'm not sure this is an issue with `ember-cli-postcss` (actually most likely it isn't) but you'll tell me and probably help me convert the Ember project to a non-ember one using just Postcss so we can open an issue at the correct place.

[Here is the reproduction](https://github.com/boris-petrov/ember-cli-postcss-bug). `npm install` and then `ember serve` - it will stop at the `PostcssCompiler` stage and take 100% CPU and never finish. The problematic combination is importing Bootstrap in `app.scss` and adding `postcss-color-hex-alpha` as a plugin in `ember-cli-build.js`. When either is removed, `ember serve` works fine.

Any ideas?

**Comment by jeffjewiss** [comment]
Hi @boris-petrov, I'm able to successfully reproduce the issue using your repo.

I think it's an issue with incorrect or outdated Sass somewhere in `bootstrap-sass` v3. I tried using `bootstrap@next` (v5) and changed the include path and it compiled (and started ember server) without an issue.

Sorry, I'm unable to help with debugging bootstra-sass v3 further, but I'd suggest upgrading if your'e able to. I believe you can use v4 from the main repo.

Cheers

**Comment by boris-petrov** [comment]
@jeffjewiss - thanks! Upgrading is not trivial so we're stuck on Bootstrap 3 for now. I've opened an issue in `postcss-color-hex-alpha`, let's see what they have to say. I'll close this issue, thanks!
