### ISSUE TITLE
Ember canary error - Uncaught ReferenceError: Ember is not defined

### ISSUE THREAD

**Issue by josemarluedke** [jeffjewiss/ember-cli-postcss#745]
In Ember canary, there is no Ember global. This error is coming from 

```Ember.libraries.register('Ember Postcss', '7.0.0');```

https://github.com/jeffjewiss/ember-cli-postcss/blob/master/index.js#L116

**Comment by jeffjewiss** [comment]
Could you please try https://github.com/jeffjewiss/ember-cli-postcss/pull/763 and let me know if that works?

**Comment by josemarluedke** [comment]
@jeffjewiss  #763 does fix the issue.

**Comment by jeffjewiss** [comment]
#763 has now been merged, so this should be fixed by v7.0.2

Please reopen the issue if this continues to be a problem. Thanks!
