### ISSUE TITLE
Vulnerability in merge package before 2.1.1

### ISSUE THREAD

**Issue by mjzefeldt** [jeffjewiss/ember-cli-postcss#752]
Looks like merge has security issue: [https://www.npmjs.com/advisories/1666](https://www.npmjs.com/advisories/1666)
Could maintainer please bump to version 2.1.1 or later?  Thanks!

**Comment by jeffjewiss** [comment]
Fixed via https://github.com/jeffjewiss/ember-cli-postcss/commit/55712f32b1fadd14d089f0e42d7aa0d79be6e1bc

Version 7.0.1 should contain merge 2.1.1 or later.
