### ISSUE TITLE
Cannot use `cssnano` in version 7

### ISSUE THREAD

**Issue by boris-petrov** [jeffjewiss/ember-cli-postcss#811]
[Here is a reproduction](https://github.com/boris-petrov/ember-cli-postcss-7-bug/tree/cssnano). Note that this is a branch in the repo, the `master` branch is for a [different](https://github.com/jeffjewiss/ember-cli-postcss/issues/725) issue.

Using `cssnano` doesn't work at all with ` ember-cli-postcss` version 7. It seems to pass the plugins defined in the `filter` block in `ember-cli-build` as plugins to `cssnano` (which I guess has some plugin mechanism) and that breaks badly as it expects completely different things.

To reproduce - clone the repo, checkout the branch, `npm install`, `ember serve`.

**Comment by boris-petrov** [comment]
@jeffjewiss - indeed, that does fix the issue! However, this is a workaround and not a real fix so let's keep the issue open until it's fixed. Thank you! :)

**Comment by jeffjewiss** [comment]
Glad to hear that fixed it. I think it's because we're merging the options recursively, but I'm not sure when I'll have a chance to work on a fix.

**Comment by gitKrystan** [comment]
I ran into this and `options: { preset: 'default' }` fixed it for me.

**Comment by jeffjewiss** [comment]
@gitKrystan thanks for sharing a working config.

I'm going to close this out since that config should solve the issue.
