### ISSUE TITLE
ember-cli-postcss v7.1.0 has a breaking change as it's requires Node.js 14 now

### ISSUE THREAD

**Issue by SergeAstapov** [jeffjewiss/ember-cli-postcss#838]
@jeffjewiss do you mind to rollback to preview supported Node.js versions in v7.x and release v8.x with min Node.js bump?

**Comment by jeffjewiss** [comment]
Yes, sorry about that. I made an assumption about the most common Node version due to its LTS status.

I should be able to publish a new minor version rolled back to the code from v7.0.x and re-release as v8 later this afternoon.

**Comment by jeffjewiss** [comment]
I've published both v7.2.0 and v8.0.0.

Thanks for quickly submitting this issue.

Please re-open this if v7.2.0 doesn't solve the Node.js version issue.

Thanks!

**Comment by SergeAstapov** [comment]
@jeffjewiss Thank you! This fixes the issue!

**Comment by boris-petrov** [comment]
@jeffjewiss - I don't see version 8.0.0 in [npm](https://www.npmjs.com/package/ember-cli-postcss) though.

**Comment by jeffjewiss** [comment]
@boris-petrov thanks for catching this! Looks like the publish failed the first time and I missed the notice. 8.0.0 should be there now.
