### ISSUE TITLE
Node 12 dropped too early?

### ISSUE THREAD

**Issue by andreyfel** [jeffjewiss/ember-cli-postcss#856]
Node 12 EOL is 2022-04-30, so, it should still be supported. Are there any real requirements to drop it?

**Comment by jeffjewiss** [comment]
When upgrading some dependencies to patch some security vulnerabilities it was more or less required to support Node 14+ moving forward.

However, ember-cli-postcss v8 and v7 are equivalent feature wise. Are you able to use ember-cli-postcss v7.2.0? 

I try to focus on the LTS version and not the maintenance version. I'm happy to apply patches to v7 of ember-cli-postcss if that would help.
