### ISSUE TITLE
Filter deprecation warnings  

### ISSUE THREAD

**Issue by ashrajagopal** [jeffjewiss/ember-cli-postcss#886]
Is it possible to add a flag to silence or filter repeated deprecation warnings so we see only 1 for example? 

`postcssOptions: {
      compile: {
        extension: 'scss',
        enabled: true,
        parser: cssParser,
        map: false,
        plugins: [sassPlugin],
      },
    }
`

The one we're seeing is `Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`

Thanks!

**Comment by jeffjewiss** [comment]
You should be able to solve this by changing the options passed to dart-sass. It looks like there's a `quietDeps` option you can toggle: https://github.com/sass/dart-sass/issues/1559#issuecomment-1030664344
